import turtle
screenwindow=turtle.Screen()
screenwindow.bgcolor("lightgreen")

sunil=turtle.Turtle()
sunil.pensize(5)

sudip=turtle.Turtle()
sudip.color("blue")
sunil.forward(120)
sunil.left(120)
sunil.forward(120)
sunil.left(120)
sunil.forward(120)
sunil.left(120)
sunil.right(180)
sunil.forward(60)
sudip.forward(60)
sudip.left(90)
sudip.forward(60)
sudip.left(90)
sudip.forward(60)
sudip.left(90)
sudip.forward(60)
sudip.left(90)
sudip.forward(60)
sudip.left(90)

screenwindow.exitonclick()